# Generated by Django 3.2.8 on 2022-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_vid_pat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='pat',
            field=models.FileField(upload_to='media/videos'),
        ),
    ]
