# Generated by Django 3.2.8 on 2022-02-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_vid_pat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vid',
            old_name='pat',
            new_name='path',
        ),
    ]
