# Generated by Django 3.2.8 on 2021-11-12 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20000)),
                ('emale', models.EmailField(max_length=30000)),
                ('subject', models.CharField(max_length=20000)),
                ('text', models.TextField(max_length=500000)),
                ('date', models.DateField(default=datetime.datetime(2021, 11, 12, 8, 53, 28, 635686, tzinfo=utc))),
            ],
        ),
    ]
