# Generated by Django 3.2.8 on 2022-01-08 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='medi/user pics'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 9, 44, 47, 942980, tzinfo=utc)),
        ),
    ]
