# Generated by Django 3.2.8 on 2022-01-14 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220108_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 17, 1, 17, 402171, tzinfo=utc)),
        ),
    ]
