# Generated by Django 3.2.8 on 2022-02-11 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_massage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 16, 12, 41, 643648, tzinfo=utc)),
        ),
    ]
