# Generated by Django 3.2.8 on 2022-02-15 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_massage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 17, 8, 1, 758192, tzinfo=utc)),
        ),
    ]
