# Generated by Django 3.2.8 on 2022-02-16 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_massage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 8, 29, 24, 950256, tzinfo=utc)),
        ),
    ]
