# Generated by Django 3.2.8 on 2022-02-24 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20220224_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 10, 19, 12, 617735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massage',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user pics/'),
        ),
    ]
