# Generated by Django 3.2.8 on 2021-11-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('category1', models.CharField(blank=True, max_length=2000, null=True)),
                ('category2', models.CharField(blank=True, max_length=2000, null=True)),
                ('category3', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='article_photos')),
                ('intro', models.TextField(blank=True, max_length=300000, null=True)),
                ('bold_text', models.TextField(blank=True, max_length=300000, null=True)),
                ('text', models.TextField(blank=True, max_length=300000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=30000)),
                ('website', models.URLField(blank=True, max_length=3000, null=True)),
                ('text', models.TextField(max_length=40000)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
