# Generated by Django 3.2.8 on 2021-11-07 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Date',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2021, 11, 7, 8, 37, 8, 606367, tzinfo=utc), default=datetime.datetime(2021, 11, 7, 8, 37, 8, 606367, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='coment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2021, 11, 7, 8, 37, 8, 607367, tzinfo=utc), default=datetime.datetime(2021, 11, 7, 8, 37, 8, 607367, tzinfo=utc)),
        ),
    ]
