# Generated by Django 3.2.8 on 2021-11-12 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211107_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2021, 11, 12, 8, 53, 28, 662688, tzinfo=utc), default=datetime.datetime(2021, 11, 12, 8, 53, 28, 662688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/article_photos'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2021, 11, 12, 8, 53, 28, 664688, tzinfo=utc), default=datetime.datetime(2021, 11, 12, 8, 53, 28, 664688, tzinfo=utc)),
        ),
    ]
