# Generated by Django 3.2.8 on 2022-01-08 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211112_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 8, 9, 44, 47, 946980, tzinfo=utc), default=datetime.datetime(2022, 1, 8, 9, 44, 47, 946980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 8, 9, 44, 47, 947980, tzinfo=utc), default=datetime.datetime(2022, 1, 8, 9, 44, 47, 947980, tzinfo=utc)),
        ),
    ]
