# Generated by Django 3.2.8 on 2022-01-14 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220108_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 14, 17, 1, 17, 421172, tzinfo=utc), default=datetime.datetime(2022, 1, 14, 17, 1, 17, 422172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 14, 17, 1, 17, 423172, tzinfo=utc), default=datetime.datetime(2022, 1, 14, 17, 1, 17, 423172, tzinfo=utc)),
        ),
    ]
