# Generated by Django 3.2.8 on 2022-01-15 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220114_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 15, 9, 23, 46, 171543, tzinfo=utc), default=datetime.datetime(2022, 1, 15, 9, 23, 46, 171543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 1, 15, 9, 23, 46, 171543, tzinfo=utc), default=datetime.datetime(2022, 1, 15, 9, 23, 46, 171543, tzinfo=utc)),
        ),
    ]
