# Generated by Django 3.2.8 on 2022-02-11 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220115_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 11, 16, 12, 41, 644648, tzinfo=utc), default=datetime.datetime(2022, 2, 11, 16, 12, 41, 644648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 11, 16, 12, 41, 645648, tzinfo=utc), default=datetime.datetime(2022, 2, 11, 16, 12, 41, 645648, tzinfo=utc)),
        ),
    ]
