# Generated by Django 3.2.8 on 2022-02-15 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220211_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 15, 17, 8, 1, 760192, tzinfo=utc), default=datetime.datetime(2022, 2, 15, 17, 8, 1, 760192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 15, 17, 8, 1, 761192, tzinfo=utc), default=datetime.datetime(2022, 2, 15, 17, 8, 1, 761192, tzinfo=utc)),
        ),
    ]
