# Generated by Django 3.2.8 on 2022-02-16 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220215_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 16, 8, 29, 24, 952257, tzinfo=utc), default=datetime.datetime(2022, 2, 16, 8, 29, 24, 952257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 16, 8, 29, 24, 953257, tzinfo=utc), default=datetime.datetime(2022, 2, 16, 8, 29, 24, 953257, tzinfo=utc)),
        ),
    ]
