# Generated by Django 3.2.8 on 2022-02-16 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220216_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 16, 9, 22, 28, 551348, tzinfo=utc), default=datetime.datetime(2022, 2, 16, 9, 22, 28, 551348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 16, 9, 22, 28, 553348, tzinfo=utc), default=datetime.datetime(2022, 2, 16, 9, 22, 28, 553348, tzinfo=utc)),
        ),
    ]
