# Generated by Django 3.2.8 on 2022-02-24 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220216_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 24, 8, 37, 38, 663644, tzinfo=utc), default=datetime.datetime(2022, 2, 24, 8, 37, 38, 663644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2022, 2, 24, 8, 37, 38, 665645, tzinfo=utc), default=datetime.datetime(2022, 2, 24, 8, 37, 38, 665645, tzinfo=utc)),
        ),
    ]
