# Generated by Django 3.2.8 on 2021-11-05 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=3000, null=True)),
                ('Text', models.TextField(blank=True, max_length=400000, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products pics')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products pics')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products pics')),
                ('category1', models.CharField(blank=True, max_length=3000, null=True)),
                ('category2', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
