# Generated by Django 3.2.8 on 2021-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
