# Generated by Django 3.2.8 on 2021-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producs', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='medi/products pics'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products pics'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products pics'),
        ),
    ]
